trignoclient_ros/Sensor[] sensors # sensor descriptors to record
duration time                     # duration of recording. if <= 0.0, continuous (no auto-stop)
string file                       # file to export data to (relative to *target_root* param). If empty, data is not exported
---
string message
bool success