trignoclient_ros/Sensor[] sensor # sensor descriptors to record
std_msgs/Duration duration_ms # duration of recording. if <= 0.0, continuous (no auto-stop)
string export_path # file to export data to. If empty, data is not exported
---
string message
bool success